### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by howardjones** [eblot/pybootd#11]
I'm looking at this now for myself - have got as far as something that doesn't immediately die, but needs work on all the buffer-manipulation stuff. Is there already work in progress, or would a PR be welcomed?

I'd also like to extract the IP-allocation and access control stuff into separate classes so that they can be replaced - my intended use is as a DHCP server integrated with an automated build server.

**Comment by howardjones** [comment]
Closing. I hadn't noticed the LGPL license, so I won't be able to work on this.

**Comment by eblot** [comment]
There is actually no reason for LGPL ... it's a 7 years old project, the original work does not seem to be under LGPL. I'm not even sure you LGPL would apply to a Python source code (given that is is already a mess to understand with compiled C code)...

Moreover I'm not a *GPL fan, I do prefer MIT license scheme.

Would it be ok for you if this project move to a BSD 3 clause / MIT license ?
