### ISSUE TITLE
pybootd fails If the host has IP addresses with 169.254.0.0/16 addresses

### ISSUE THREAD

**Issue by alexpilotti** [eblot/pybootd#4]
Pybootd fails is the host contains interfaces where the netmask is not set, for example in case on auto assigned RFC 3927 IPs (169.254.0.0./16).

Fixed by: https://github.com/cloudbase/pybootd/commit/5b7e75676476392d47f72d48490b3e20f3f7571e

**Comment by eblot** [comment]
Patch applied
