### ISSUE TITLE
[hundle dhcp packet] extra buffer chained into the end of the return packet (after the packet end option 255).

### ISSUE THREAD

**Issue by ahmadm** [eblot/pybootd#6]
extra buffer chained into the end of the DHCP return-packet (after the end option 255),
this extra buffer appears like a padding section, so client cannot recognize all the extra options.

I think DHCP_END option should be chained after the extra_buf, not before.

```
    *pkt += struct.pack('!BB', DHCP_END, 0)*

    if pxe:
        extra_buf = self.build_pxe_options(options, server)
        if not extra_buf:
            return
    else:
        extra_buf = self.build_dhcp_options(hostname) 
```

regards

**Comment by eblot** [comment]
You are right. Good catch, thanks.
